import { MainSkill, LibSkill, ServeSkill, SkillSubWrap, SkillWrapper, SkillsWrap, SkillsWrapper, LibSkillWrap} from "../style/Skill.styled"

export const Skill = () => {
    return(
        <>
            <SkillWrapper>
                <SkillSubWrap> SKILL</SkillSubWrap>
                <SkillsWrapper>
                    <MainSkill>
                        <SkillsWrap>
                            JavaScript
                        </SkillsWrap>
                        <SkillsWrap>
                            REACT
                        </SkillsWrap>
                        <SkillsWrap>
                            LINUX
                        </SkillsWrap>
                        <SkillsWrap>
                            Node.js
                        </SkillsWrap>
                        <SkillsWrap>
                            MySQL
                        </SkillsWrap>
                    </MainSkill>
                    <ServeSkill>
                        <SkillsWrap>
                            Mac OS
                        </SkillsWrap>
                        <SkillsWrap>
                            Windows
                        </SkillsWrap>
                        <SkillsWrap>
                            CentOS
                        </SkillsWrap>
                        <SkillsWrap>
                            Linux
                        </SkillsWrap>
                        <SkillsWrap>
                            Axios
                        </SkillsWrap>
                    </ServeSkill>
                    <LibSkill>
                        <SkillsWrap>
                            Redux
                        </SkillsWrap>
                        <LibSkillWrap>
                            React-Redux
                        </LibSkillWrap>
                        <LibSkillWrap>
                            Styled-components
                        </LibSkillWrap>
                        <LibSkillWrap>
                            React Router
                        </LibSkillWrap>
                    </LibSkill>
                    <ServeSkill>
                        <SkillsWrap>
                            NOTION
                        </SkillsWrap>
                        <SkillsWrap>
                            TRELLO
                        </SkillsWrap>
                        <SkillsWrap>
                            FIGMA
                        </SkillsWrap>
                        <SkillsWrap>
                            GIT
                        </SkillsWrap>
                        <SkillsWrap>
                            GITHUB
                        </SkillsWrap>
                    </ServeSkill>
                </SkillsWrapper>
            </SkillWrapper>
        </>
    )
    }